[package]
name = "etfjs"
version = "0.1.0"
authors = ["Vlad Frangu <kingdgrizzle@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
byteorder = { version = "1.3.2", default-features = false }
js-sys = "0.3.25"
lazy_static = "1.3.0"
regex = "1.1.9"
wasm-bindgen = "0.2.48"
